### ISSUE TITLE
Mesosaurus fails to compile

### ISSUE THREAD

**Issue by theMarix** [mesosphere/mesosaurus#2]
Trying to install Mesosaurus following the instructions from the README, I run into the following issue during `sbt compile`:

```
[info] Compiling 8 Scala sources to /localdata/mbach/Mesosaurus/mesosaurus/target/scala-2.10/classes...
[error] /localdata/mbach/Mesosaurus/mesosaurus/src/main/scala/io/mesosphere/mesosaurus/Mesosaurus.scala:194: not found: value WebServer
[error]         WebServer.start
[error]         ^
[error] /localdata/mbach/Mesosaurus/mesosaurus/src/main/scala/io/mesosphere/mesosaurus/Mesosaurus.scala:198: not found: value WebServer
[error]         WebServer.stop
[error]         ^
[error] /localdata/mbach/Mesosaurus/mesosaurus/src/main/scala/io/mesosphere/mesosaurus/TaskGenerator.scala:67: not found: value WebServer
[error]         val uri = CommandInfo.URI.newBuilder().setValue(WebServer.url() + "/" + TASK_PROGRAM).setExecutable(true)
[error]                                                         ^
[error] three errors found
[error] (compile:compile) Compilation failed
```

The issue was newly introduced in f50bf4efb16fe4e7d4eab03d71b63357e2c4a14a.
